### PR TITLE
Improve converting scripts

### PR DESCRIPTION
**Pull request by DylanVanAssche**
- Improved the documentation of each script
- Ran the complete pipeline over several nights to get from the `crawler.py` to `main.py` (spliiting CSV).
- Adjusted to paths of the file to make them work in every script. Sometimes, we called the big CSV file as `complete.csv`, `the_one_file_to_rule_them_all.csv`, ...
- Maybe we need to add a pipeline workflow to the README which discuss which action you need to do in each step.? Useful for non technical people! What do you think @samvdkris

### CODE REVIEW

**Review by juliavdkris — APPROVED** [review]
Looks good! Thank you for your sacrifice. :P

For the multithreading we might want to use the built-in concurrency library (https://docs.python.org/3/library/concurrent.futures.html) instead of running multiple Python instances in the background. Just make a function for the conversion and throw it all in a pool and Python will handle the rest.

**Comment by juliavdkris** [comment]
Pipeline workflow in the README sounds like a good idea. Maybe even add a bash script that automatically runs everything in the correct order with the correct settings etc?

**Comment by DylanVanAssche** [comment]
> Pipeline workflow in the README sounds like a good idea. Maybe even add a bash script that automatically runs everything in the correct order with the correct settings etc?

Indeed, a bash script would be great, however, it takes a long time to run everything. So both seems to be a good compromise?

**Comment by DylanVanAssche** [comment]
> Looks good! Thank you for your sacrifice. :P
> 
> For the multithreading we might want to use the built-in concurrency library (https://docs.python.org/3/library/concurrent.futures.html) instead of running multiple Python instances in the background. Just make a function for the conversion and throw it all in a pool and Python will handle the rest.

Yeah, I didn't changed that approach :P I haven't a lot of experience with concurrent threads on Python.

**Comment by juliavdkris** [comment]
Yeah, both is probably the best. I'll look into the concurrency stuff when I get home (if I have time, I'm kind of busy with school). But the concurrent.futures module makes it much easier.

**Comment by DylanVanAssche** [comment]
Ah it works this way already :) so if we don't improve it, it doesn't matter a lot I guess :P

**Comment by juliavdkris** [comment]
Yeah but fancy

**Comment by DylanVanAssche** [comment]
@samvdkris Added a README update to explain the steps to generate the data set

**Pull request merged**
