### PR TITLE
Add ML prediction script

### PR DESCRIPTION
**Pull request by juliavdkris**
Python script that loads the exported model and uses it to make a prediction

### CODE REVIEW

**Comment by juliavdkris** [comment]
I made some small changes because I'm annoying, but other than that: LGTM. Nice work, man!

**Comment by DylanVanAssche** [comment]
Fortunately I can correct those ' and \t in VIM without any issue ;-) But I respect your coding style anyway. Everyone has his own principles.

Anyway, we should be consistent, my defaults are the opposite of yours. I always use 4 spaces and " (except for JS, I use single quotes there). We can't afford a code base which is a mixup of both.

Sent from ProtonMail mobile

-------- Original Message --------

**Review by DylanVanAssche — COMMENTED** [review]
Should we add the necessary data files too? Maybe not the model but the JSON URI files? This will ease our development a bit I think. The model can be added using `git lfs` though

**Review by DylanVanAssche — APPROVED** [review]
LGTM

**Pull request merged**
